import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";
import { QueryProvider } from "@/shared/providers/query-provider";
import { BettingModalProvider } from "@/shared/providers/betting-modal-provider";
import { Footer } from "@/shared/components/footer";
import { GlobalBettingModal } from "@/shared/components/global-betting-modal";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <NuqsAdapter>
          <QueryProvider>
            <BettingModalProvider>
              <Toaster richColors position="top-right" />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
              <GlobalBettingModal />
            </BettingModalProvider>
          </QueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
